.gitignore, process_report/process_report.py, process_report/tests/unit_tests.py
This reverts commit 52859c97b519be91427e45948e67e175de231db5.
=> Revert "Added ability to group invoices by PIs"

.gitignore, process_report/process_report.py, process_report/tests/unit_tests.py
Closes #7, I have modified `process_report.py` to group the merged invoices into ones grouped by PIs. These smaller CSVs will be placed in a folder of your choice, or defaults to a one placed in the working directory
=> Added ability to group invoices by PIs

process_report/process_report.py
I believe the bug comes from two lines which tries to index into the dataframe. I used an inappropriate method for indexing and this should fix it.
=> Amending commit to add ability to group invoices by PIs

process_report/process_report.py, process_report/tests/unit_tests.py
Closes #13, I have added an export function `export_lenovo()` which exports an invoice CSV following the specifications in the related issue. The list of SU types considered to be Lenovo and the SU Charge of $1 have been put into constant values defined in the function.
This PR is blocked by #12.
=> Added processing and exporting for Lenovo SU Types

README.md
Updated the README, after the #14 Lenovo PR is merged
=> Update out of date README.md

process_report/process_report.py, process_report/tests/unit_tests.py, requirements.txt, tools/clone_nonbillables_and_process.sh
Completing the first half of #21. I modified the invoice script to give the user the option to fetch invoices from S3 storage, as well as to upload them to S3. 
The filenames for invoices to be stored locally and in S3 is determined by the user. The script expects several env vars to be sent to perform authentication to S3
The connection to Backblaze B2 is done in the Python script through `boto3`.
This PR will be followed-up with a PR to containerize the invoice processing.
=> Implemented S3 integration

process_report/process_report.py
Closes #29, I've removed HU invoice processing, and added an S3 export function to specifically export the HU-BU invoice. Since the HU-BU invoice will now be exported to a (mostly) hardcoded path in S3, the user's choice of filename for the HU-BU invoice will no longer matter when it is exported to S3.
=> Removed HU invoice processing and added S3 export function for HU-BU invoice

process_report/process_report.py, requirements.txt
This will read the cost columns from collected invoices as a Decimal, using the integration between Panda and PyArrow, which allows Panda to use more data types.[0]
The decimal defined can represent numbers up to 12 significant digits and up to 3 decimal points.
[0]: https://pandas.pydata.org/docs/user_guide/pyarrow.html
=> Read cost as a Decimal from collected invoices

process_report/process_report.py, process_report/tests/unit_tests.py
Partially closes #27. If the user does not provide an old_pi file, `process_report.py` will by default fetch the file from a hardcoded location in S3 storage.
Setting the `upload-to-s3` option will now upload both the processed CSV invoices and the updated PI file.
I've also renamed some functions for consistent capitalization.
I have also added a few print statements to provide the following info:
- When a new PI is encountered in an invoice
- When a future PI is found in a past invoice
It should be noted that if future PIs are encountered when processing old invoices, the invoice script will consider them new PIs for the purpose of the new PI credit, and will update the future PI's first-month date to be same as the old invoice's date.
Blocked on #23, and prerequisite to #21
=> Added option to fetch and upload old PI file to from and to S3, and added logic to update old PI file

process_report/process_report.py, process_report/tests/unit_tests.py
Closes #25 fully, I have implemented the function to export the BU Internal invoice, following @joachimweyl's specifications in the linked issue.
The BU subsidy will be applied to every BU PI after the New-PI credit is applied to eligible PIs in the combined invoice. With how this is currently implemented, the combined invoice may NOT show BU PIs' final balances, as the BU-only invoice is made and exported after the combined invoice is exported.
The current subsidy is set at $100, but I have made the amount configurable via a cli arguement.
=> Implemented processing and exporting for BU Internal invoice

process_report/process_report.py
Switches the precision of Cost from 3 to 2. The value is rounded up as demontrated by the following block of code given the following csv file.
```csv
Cost
123.1234
123.5678
```
```python
>>> dataframe = pandas.read_csv("csv.csv", dtype={"Cost": pandas.ArrowDtype(pyarrow.decimal128(12, 2))})
>>> dataframe
Cost
0  123.12
1  123.57
```
Related https://github.com/CCI-MOC/process_csv_report/issues/35
=> Use 2 decimal points for Cost, rounding up

.github/workflows/build.yaml, Dockerfile, tools/clone_nonbillables_and_process.sh
Closes #21 completely. This PR is blocked on #27, and will containerize the billing script. A github workflow is added to build and publish the billing image. Check the second commit to see the changes which actually implemented the containerization.
=> Containerized billing script

k8/base/invoice-processing.yaml, k8/base/kustomization.yaml, k8/overlay/gh-nonbillables.yaml, k8/overlay/kustomization.yaml, k8/overlay/nerc-invoices-s3-bucket.yaml
Blocked on #31. Closes #22. The manifests needed for the cronjob includes the cronjob, and two secret files which sets the private key for the nonbillable repo's deploykey and the s3 app_key and key_id.
The cronjob is set to run at 12:00PM (Noon) on the 1st of each month. The last commit will show what's actually included in this PR.
=> Packed invoice container into Kubernetes cronjob

process_report/process_report.py
Closes #34, I've added a few small changes which should remove all pandas SettingWithCopyWarning and FutureWarning warnings. These consisted of explicit type casting, and explicitly making copies of data-frames that would later be modified
=> Updated process_report.py to avoid warnings for SettingWithCopyWarnings and FutureWarnings

process_report/process_report.py
Closes #42. I've changed when the Lenovo invoice is made and exported. Now it uses the merged invoice, before non-billables are removed.
=> Included usage of nonbillable projects in Lenovo invoice

process_report/process_report.py, process_report/tests/unit_tests.py
Finally closes #25, I've added some lines to remove duplicate projects from the BU internal invoice along with the corresponding changes to the test cases.
The cost, credit, and balance fields are now summed up before applying the subsidy.
While writing this I had to be a bit careful with knowing whether certain indexing and assignment operations were returning copies or references. I'll address this in a PR soon?
=> Removed projects duplicates when applying BU subsidy

process_report/process_report.py, process_report/tests/unit_tests.py
Closes #38, the New-PI credit will now exclude certain SU Types, configurable by a constant `EXCLUDED_SU_TYPES` in `apply_credits_new_pi()` . A test case has been added to test this functionality.
=> Prevent projects with certain SU types from being credited

process_report/process_report.py
Closes #41 `process_report.py` will now upload a backup of the PI file before it is modified during invoice processing. This is done in `fetch_s3_old_pi_file()` when the PI file is first fetched, and is noted with a comment for clarification.
=> Upload backup of PI file after processing

process_report/process_report.py, process_report/tests/unit_tests.py
Closes #43. Added an argument `alias-file` which gives the user the choice to provide a PI alias file, else defaults to fetching the file from a hardcoded location in S3 storage ("PIs/alias.csv")
The PI file must be a csv, with the first value of each row being the canonical name for each PI every other value in each row will be the PI's known aliases.
An example:
```
PI1,PI1_1,PI1_2
PI2,PI2_1
```
Given the alias file, `validate_pi_aliases` will iterate through all projects in the combined invoice, and replace all encountered aliases with its PI's canonical name
=> Validate combined dataframe with alias file

process_report/process_report.py, process_report/tests/unit_tests.py
Closes #37. I apologize for the large PR. I did not expect a feature summarized in 8 words would take this long...
Implementing second-month tracking requires the reformatting of the PI file, which I have created outside of this PR following the specifications in #37. That being said, the invoice processing script will now require a PI csv file containing the follow columns:
- PI
- First Invoice Month
- Initial Credits
- 1st Month Remainder
- 2nd Month Remainder
The most significant changes are the addition of some datetime utility functions, and mainly `apply_credits_new_pi()`. I've also re-written how the test case for applying the new-PI credit is done. Now the output invoice is directly compared to an answer Dataframe, and the modified PI file is directly compared to a list of …
=> Added tracking of New-PI credit usage for second month

process_report/process_report.py
Closes #56. Some of our rates may be have very low values, i.e 0.0000009, which may be displayed in scientific notation if read as a float by pandas.read_csv() Specifying the field type as str suppresses this behavior.
=> Loads invoice "rate" field as string to suppress scientific notation representation

process_report/process_report.py
In cases where the `2nd Month Used` field for some PIs are empty in the old PI file, not having the NA check would result in an error
In the future, all PI entries should no longer have empty fields, given how this script initilizes new PI entries, so this change might not be completely nessecary. Nonetheless, it's good to check all our bases?
=> Added NA check for empty `2nd Month Used` field

process_report/institute_map.json
The two new domains added were not written properly, such that PIs with the email domains dartmouth.edu or chemistry.harvard.edu would never be matched
=> Fixed the two new domains

process_report/invoices/invoice.py, process_report/invoices/lenovo_invoice.py, process_report/invoices/nonbillable_invoice.py, process_report/process_report.py, process_report/tests/unit_tests.py, process_report/util.py
Closes #63 . This refactor commit is the first of a few, to lay out initial structure
A new submodule, `invoices`, is added, containing a base class `Invoice` which is inherited by all other invoices. Currently, only the lenovo and nonbillable invoice has classes which inherits from `Invoice` Also created and partially populated an `util.py` file, containing functions placed above `main()` in `process_report.py` After the refactoring process is fully complete,
these utility functions will be completely removed from `process_report.py`
I can already tell I am breaking several Python conventions, so I am ready.
=> Initial refactoring of process_report

process_report/invoices/billable_invoice.py, process_report/invoices/invoice.py, process_report/process_report.py, process_report/tests/unit_tests.py, process_report/tests/util.py, process_report/util.py
Closes #64, I have refactored the billable invoice. I'll explain in more detail below, and have also have a question that I would like the professionals' opinions on.
For some context, the billable invoice performs 2 preparation steps (removing nonbillables and validating PI names) and 3 distinct steps during processing (loading the old PI file, applying the new PI credit, and then writing back the old PI file). I decided to split these steps into their own functions, and to store those functions in `util.py`, instead of making them private functions in the`BillableInvoice` class.
As for the test cases, I created a new test class for the billable invoice. Note that this new test case uses randomly generated values, instead of a hardcoded dataframe. I figured this would be more robust? …
=> Refactored billable invoice

process_report/invoices/hu_bu_invoice.py, process_report/process_report.py
Closes #68. Not necessarily dependent on #61, but is part of the overall refactor process. Aside from the addition of `hu_bu_invoice.py`, I decided to cache the results of `get_invoice_bucket()` using [functools](https://docs.python.org/dev/library/functools.html#functools.lru_cache)
While refactoring, I noticed that I didn't add code to upload the BU Internal invoice to S3, and also forgot to remove some [functions](https://github.com/CCI-MOC/process_csv_report/blob/abe2deb8da7bafb1682018da6fef090937caac2c/process_report/process_report.py#L49-L59) from `process_report.py` that have been [moved](https://github.com/CCI-MOC/process_csv_report/blob/abe2deb8da7bafb1682018da6fef090937caac2c/process_report/util.py#L10-L17) to `utils.py`. @naved001 @knikolla Should these be part of a separate …
=> Refactored the HU-BU invoice

process_report/invoices/NERC_total_invoice.py, process_report/process_report.py
Closes #83, I renamed `hu_bu_invoice.py` to `NERC_total_invoice.py`, grouped the institutions being exported in this invoice into a class constant list, and added URI.
=> Renamed HU-BU invoice and added URI

process_report/invoices/billable_invoice.py, process_report/invoices/bu_internal_invoice.py, process_report/invoices/discount_invoice.py, process_report/process_report.py, process_report/tests/unit_tests.py, process_report/tests/util.py, process_report/util.py
Closes #67. A new `bu_internal_invoice.py` file has been added. Note that the BU Internal invoice depends on the billable invoice. The test case for the BU Internal invoice has been modified appropriately.
=> Refactored BU Internal Invoice

process_report/invoices/pi_specific_invoice.py, process_report/process_report.py, process_report/tests/unit_tests.py, process_report/tests/util.py
Closes #69. The PI-specific is now implemented in the `PIInvoice` class. This class takes in the entire billable invoice and will export the PI invoices to local storage and S3. Because of its unique export file paths, it overrides the `export()`
Note that to follow the file path has changed slightly, from:
`f"{self.name}/{pi_instituition}_{pi}_{self.invoice_month}.csv"`
to...
`f"{self.name}/{pi_instituition}_{pi} {self.invoice_month}.csv"`
Note that replacement of the "_" to " ". I do this to be more consistent with the filename pattern for the other invoices.
Aside from that, I've also removed `upload_to_s3()` and its corresponding unit test, since it is no longer needed (after this PR, and certainly after all the refactor PRs are merged). @knikolla @naved001 Should I add a test for …
=> Refactored PI-specific invoices

Dockerfile, process_report/institute_list.yaml, process_report/invoices/billable_invoice.py, process_report/process_report.py, process_report/tests/unit_tests.py, process_report/tests/util.py, process_report/util.py, requirements.txt
Closes #94, `process_report.py` will now use `nerc_rates` to determine if the New-PI credit is limited to institutions that are MGHPCC partners for the given invoice month.
The script determines whether an institution's MGHPCC partnership is active by first seeing if the `mghpcc_partnership_start_date` field is set in `institute_list.yaml`, then checks if the start date is within or before the invoice month.
@joachimweyl To mark an institution as an MGHPCC partner, you will need to set the field `mghpcc_partnership_start_date` in `institute_list.yaml` to the start date of the partnership in YYYY-MM format.
I.e for Boston University, their current entry looks like this:
```
-   display_name: Boston University
domains:
- bu.edu
- robbaron
```
To mark them as a partner, change their entry …
=> Allow limiting New-PI credit to partner institutions

process_report/invoices/NERC_total_invoice.py, process_report/invoices/billable_invoice.py, process_report/invoices/bu_internal_invoice.py, process_report/invoices/invoice.py, process_report/invoices/lenovo_invoice.py, process_report/invoices/nonbillable_invoice.py, process_report/invoices/pi_specific_invoice.py, process_report/tests/unit_tests.py
Closes #100. Two class attributes, `export_columns_list` and `exported_columns_map`, has been added to `Invoice`, along with a class function `_filter_columns()`. Subclasses of `Invoice` must now define `export_columns_list`, containing the ordered list of columns that must be exported in their respective invoices. Subclasses can optional define `exported_columns_map`, containing mappings between "internal" column names and what their name should be when exported.
The field name `RATE_FIELD` has been added to `invoice.py`. It was previously forgotten.
=> Allow invoice subclasses to explicitly declare their exported columns and column names

process_report/process_report.py, process_report/processors/add_institution_processor.py, process_report/processors/processor.py, process_report/processors/validate_pi_alias_processor.py, process_report/tests/unit_tests.py, process_report/tests/util.py, process_report/util.py
Closes #99. Somewhat dependant on #100. A `Processor` class has been added, subclassing from the `Invoice` class. This is the first step to refactor invoicing in order to seperate the processing and filtering/exporting functionalities of our current `Invoice` subclasses. Subclasses of `Processor` should only process invoices and manipulate its internal data, while subclasses of `Invoice` should only perform filtering and exporting, never changing any data itself.
In addition to implementing `Processor`, two of its subclasses, `ValidatePIAliasProcessor` and `AddInstitutionProcessor` has been added to perform some preliminary processing steps.
=> Implemented `Processor` class and refactored some preliminary processing 

process_report/invoices/NERC_total_invoice.py, process_report/invoices/billable_invoice.py, process_report/invoices/bu_internal_invoice.py, process_report/invoices/invoice.py, process_report/invoices/pi_specific_invoice.py, process_report/process_report.py, process_report/processors/discount_processor.py, process_report/processors/new_pi_credit_processor.py, process_report/tests/unit_tests.py, process_report/tests/util.py
Closes #101. Depends on #108. I've implemented processor for applying the New-PI Credit, and included a new field to distinguish between the PI balance and the NERC balance. More details are in my commit message.
There are two commits to this PR, starting with `Initialized processor for applying the New-PI Credit and discounts`. The first one only copies over code, while the second commit actually makes functional changes.
=> Implemented processor for New-PI credit

process_report/invoices/pi_specific_invoice.py
While test-running my code, I discovered that I forgot to change a part in `pi_specific_invoice.py` that had become deprecated after merging #119. Before this PR, `self.export_data` would be assigned to a None value, instead of the actual export data.
My apologies. I should have tested my code more thoroughly myself.
=> Fixed reference to `self.export_data` in pi-specific invoice

process_report/invoices/billable_invoice.py, process_report/process_report.py, process_report/processors/add_institution_processor.py, process_report/processors/new_pi_credit_processor.py, process_report/util.py
Closes #121. I apologize for my foolishness.
=> Replaced print statements with `logger` calls

process_report/process_report.py
Closes #130
All values in nerc-rates are of type string and
need to be correctly interpreted by the caller.
Value for Limit New PI Credit to MGHPCC Partners is of type string and value "True" and is being passed as such to a method expecting a boolean.
This change add a comparison with the string "True" to perform the conversion.
=> Correctly convert nerc-rates value to boolean

process_report/invoices/NERC_total_invoice.py
Closes #125. Consists of the last commit
=> Included projects belonging to MGHPCC-managed groups in the NERC total invoice

Dockerfile, process_report/invoices/pi_specific_invoice.py, process_report/templates/pi_invoice.html, process_report/tests/unit/invoices/test_pi_specific_invoice.py, requirements.txt
Closes #84. This PR consists of the last commit.
This PR mostly involved changes to the pi-specific invoice class. More details in the commit message. Two Python packages were crucial for this task, [Jinja](https://jinja.palletsprojects.com/en/stable/) and [Selenium](https://www.selenium.dev/documentation/) 
@knikolla @larsks I am aware that running the invoice script with this change will make pandas print a bunch of `FutureWarnings` for each PDF printed. Should I address them after the current state of the PR is approved?
=> PI invoices are now exported as PDFs

process_report/process_report.py, process_report/processors/new_pi_credit_processor.py, process_report/tests/util.py
Closes #147. In addition to fetching the BU subsidy, I decided to also fetch the New-PI credit. These values can optionally be provided through the CLI.
Also, some if-clauses have been refactored for cleanliness.
=> The BU subsidy and New-PI credit can now be fetched from nerc_rates

process_report/institute_list.yaml, process_report/invoices/NERC_total_invoice.py
Closes #138  The means the `INCLUDED_INSTITUTIONS` from `NERCTotalInvoice` is now removed.
=> Added `include_in_NERC_total_invoice` field to `institute_list.yaml`

process_report/invoices/prepay_credits_snapshot.py, process_report/process_report.py, process_report/tests/unit/invoices/test_credits_snapshot.py, process_report/tests/util.py
Closes #86. This PR consists of only the last commit, "NERC Prepay Credits...". 
Two functions have been added to the Prepayment Processor. One is to obtain the credits "snapshot". A test case has been written for this function.
=> Allow exporting a snapshot of NERC Prepay Credits file

.github/workflows/pre-commit.yaml, .github/workflows/unit-tests.yaml, .github/workflows/validate-institute-list.yaml
update CI files to python version 3.12 to accommodate changes in get_value_at from nerc-rates
=> update CI python version to 3.12 and specify python version in precommit.yaml

process_report/process_report.py, process_report/processors/coldfront_fetch_processor.py, process_report/tests/unit/processors/test_coldfront_fetch_processor.py, process_report/tests/unit/test_util.py, process_report/tests/util.py
Closes #153. Authentication to Coldfront must be done through Keycloak by providing the client id and secret. These can be set through env vars (`KEYCLOAK_CLIENT_ID` and `KEYCLOAK_CLIENT_SECRET`). A Keycloak and Coldfront url can optionally be provided. They default to the ones hosted by the MGHPCC.
The processor is responsible for adding the PI email and institute code to invoices.
If a Coldfront allocation for an invoice project could not be found, and this project also happens to be
billable, a warning will be logged.
**The query to the Coldfront allocation API will only ask for allocations that appeared on the invoice**
Test cases have been added.
=> Implemented processor to fetch Coldfront allocation data

process_report/invoices/NERC_total_invoice.py, process_report/processors/prepayment_processor.py, process_report/tests/unit/processors/test_prepayment_processor.py
In the prepay contacts csv, the `MGHPCC Managed` field contains a "Yes" or "No" string, and would be loaded as a string by `pandas.load_csv`. Previously, the `MOCA_prepaid_invoice` [incorrectly assumed](https://github.com/CCI-MOC/invoicing/blob/9ce1ab292df40fb75f2099de86b89fd8683b445e/process_report/invoices/MOCA_prepaid_invoice.py#L41) the `GROUP_MANAGED_FIELD` was a boolean, leading to a bug in billing. 
Fortunately, we don't have any prepay projects yet, so the impact of this is 0 (other than people's review time (I'm sorry)).
The prepay test case has been updated.
=> Convert prepay managed field into Boolean

process_report/invoices/NERC_total_invoice.py, process_report/tests/unit/invoices/test_nerc_total_invoice.py, process_report/tests/util.py
After creating the Pydantic model for the institute list, I forgot to update how the NERC invoice references the display name.
=> Fixed bug where NERC total invoice incorrectly references institute display name

process_report/invoices/invoice.py, process_report/processors/coldfront_fetch_processor.py, process_report/processors/validate_billable_pi_processor.py, process_report/tests/unit/processors/test_coldfront_fetch_processor.py, process_report/tests/unit/processors/test_validate_billable_pi_processor.py
Closes #165. More details in the commit message. This is blocking #167 and #152.
I have a feeling this solution for the `ocp-test` debacle is a bit clunky. Let me know what you guys think.
=> Added nonbillable cluster list to billable processor

process_report/process_report.py, process_report/processors/coldfront_fetch_processor.py, process_report/tests/unit/test_util.py, process_report/tests/util.py
Closes #194. The filepath to a JSON file can be now passed through the CLI. This will allow injection of custom Coldfront data for ease of testing purposes.
=> Added CLI option to pass in Coldfront API data

.github/workflows/chromium-validation.yaml, process_report/tests/unit/test_chromium.py
Closes #145. Adds integration test to verify that PDF generation via headless Chrome works as expected. This ensures continued compatibility as Chromium evolves.
Brought up in: https://github.com/CCI-MOC/invoicing/issues/145#issue-2796145953
=> Add integration test for headless Chrome PDF generation. 

process_report/process_report.py
The cli argument for the invoice was never passed, so it just had a blank name like `<YYYY-MM>.csv`.
=> Fixed ocp test invoice not given a name

.github/workflows/integration-tests.yaml, process_report/invoices/pi_specific_invoice.py, process_report/tests/integration/test_chromium.py, process_report/tests/unit/invoices/test_pi_specific_invoice.py
Relocate tests/unit/test_chromium.py to tests/integration/test_chromium.py.
The chromium test is not a unit test -- it has an external dependency on
Chromium. By relocating it to tests/integration, we ensure that the unit
tests run without errors.
This commit also contains some minor changes to suppress warnings from
strict type checkers.
=> Chromium test is not a unit test

.github/workflows/integration-tests.yaml, .github/workflows/unit-tests.yaml, process_report/tests/integration/test_chromium.py, process_report/tests/unit/invoices/test_base_invoice.py, process_report/tests/unit/invoices/test_credits_snapshot.py, process_report/tests/unit/invoices/test_nerc_total_invoice.py, process_report/tests/unit/invoices/test_pi_specific_invoice.py, process_report/tests/unit/processors/test_add_institution_processor.py, process_report/tests/unit/processors/test_bu_subsidy_processor.py, process_report/tests/unit/processors/test_coldfront_fetch_processor.py, process_report/tests/unit/processors/test_lenovo_processor.py, process_report/tests/unit/processors/test_new_pi_credit_processor.py, process_report/tests/unit/processors/test_prepayment_processor.py, process_report/tests/unit/processors/test_validate_alias_processor.py, process_report/tests/unit/processors/test_validate_billable_pi_processor.py, process_report/tests/unit/processors/test_validate_cluster_name_processor.py, process_report/tests/unit/test_institute_list_validate.py, process_report/tests/unit/test_util.py
Closes #220. Update test workflows to use `pytest`
As suggested before[1], `unittest` assertions are now replaced 
with normal asserts to utilize  `pytest`'s better error logging. 
Corresponding changes made to workflows.
[1] https://github.com/CCI-MOC/invoicing/issues/220#issuecomment-3074211605
=> Replace unittest assert with pytest asserts
